
import { BASE_URL } from "../../../utils/api/base";
import { TextField,Button, Stack, Container, AppBar,Toolbar,Typography } from "@mui/material";
import { useState } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import AdaptationReviewCard from "../../../components/AdaptationReviewCard";

export async function getServerSideProps(context) {
    const {q}=context.query;
    const resp=await fetch(BASE_URL+"/reviews?q="+q);
    const data=await resp.json();

    return {
        props:{
            reviews:data
        }
    }   
}

export default function index({reviews}) {
      const [search,setSearch]=useState("");
      const router=useRouter()
    
  return (<>
  <Head>
        <title>Adaptation Reviews.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar position="relative">
        <Toolbar>
          <Typography variant="h6" color="inherit" noWrap>
            Adaptations Reviews
          </Typography>
        </Toolbar>
      </AppBar>

  <Container>
  <Stack direction={"row"} sx={{m:2}}>
   <TextField fullWidth value={search} onChange={(e)=>setSearch(e.target.value)}></TextField>
                <Button variant='contained' onClick={()=>{ router.push("/review/search?q="+search)}}>
                  Search
                </Button></Stack>
    <div>Nomber of results: {reviews.length || 0}</div>
    {reviews.map((adaptation, index)=> {
                return <AdaptationReviewCard
                    key={index}
                    id={adaptation.id}
                    rating={adaptation.rating}
                    title={adaptation.title}
                    comment={adaptation.comment}
                  />
              })}
    </Container>
    </>
  )
}
