import TodoList from "@/components/TodoList";
import { Grid, Box, Stack } from "@mui/material";
import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [inputText, setInputText] = useState("");
  const [chats, setChats] = useState([]);

  function handleSelfChatButton() {
    setChats([...chats, inputText])
    setInputText("");
  }

  return (
    <>
      <Head>
        <title>Create ENxt App</title>
        <meta name="description" content="Generated by create next app"></meta>
        <meta name="viewpoint" content="width=device-with, initial-scale=1"></meta>
        <link rel="stylesheet"href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"/>
      </Head>

      <Stack direction={'row'} sx={{m:2}}>
          <Box sx={{ width: '50vw'}}>
            <input value={inputText} type="text" onChange={(e) => {
              setInputText(e.target.value);
            }}/> 
            <button onClick={handleSelfChatButton}>Self Chat</button>
            {/** Upper for inputing text */}
            <p>{inputText.toUpperCase()}</p>
            <br/>
            <br/>
            {/** Chat records */}
            {chats.map((item, index) => <p key={index}>{item}</p>)}
          </Box>
          <Box sx={{ width: '50vw'}}>
            {/** */}
            <TodoList />
          </Box>
      </Stack>
    </>
  );
}
