import {useEffect, useState} from 'react'

import Head from 'next/head'

import Typography from '@mui/material/Typography';
import Container from '@mui/material/Container';
import Box from '@mui/material/Box';

import AgencyCard from '@components/AgencyCard';
import NavBar from '@components/NavBar';

import { getAgencies } from 'utils/api/agencies'

export default function Home() {
  const [agencyData, setAgencyData] = useState([])
  // I want you to import getAgencies
  // useEffect to load the data in a stateful item.
  useEffect(()=> {
    // looad this on mount.
    loadAgencyData()
  }, [])

  const loadAgencyData = async () => {
    const data = await getAgencies()
    console.log(data)
    setAgencyData(data.results)
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <NavBar />

        <Container sx={{paddingTop:2}} component="main" maxWidth="xs">

          <Typography variant="h3">
            Space Agencies
          </Typography>
          <Box
            sx={{
              marginTop: 2,
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
            }}
          >
            {agencyData.map((agency)=> {
              return <AgencyCard
                imageUrl={agency.image_url}
                name={agency.name}
                abbreviation={agency.abbrev}
                description={agency.description}
                id={agency.id}
              />
            })}
          </Box>
        </Container>

    </div>
  )
}
