import Head from 'next/head'
import { useRouter } from 'next/router';

import Typography from '@mui/material/Typography';
import Container from '@mui/material/Container';
import Box from '@mui/material/Box';

import NavBar from '@components/NavBar';

export default function SettingsDashboard() {
  // initialize the client side routing for this component.
  const router = useRouter()

  console.log(router)
  // for the path, your variable needs to be the same
  // as the file name except removing the [].
  const {user} = router.query

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Container sx={{paddingTop:2}} component="main" maxWidth="xs">
        <Typography variant="h3">
          Settings Dashboard: {user}
        </Typography>
      </Container>
    </div>
  )
}
