import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';

import Container from '@mui/material/Container';

import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';

import {useState} from 'react'
import { Paper } from '@mui/material';

const JokeUrl = "https://official-joke-api.appspot.com/jokes/programming/random";

export default function Home() {
  const [joke, setJokes] = useState({setup:"Setup of joke", punchline:"Punchline of joke"});
  const [recentJokes, setRecentJokes] = useState([]);

  async function getNewJoke() {
    const response = await fetch(JokeUrl);
    const data = await response.json();

    // Put current joke to recentJokes list
    setRecentJokes([joke,...recentJokes]);

    // Update current joke with the new one
    setJokes(data[0]);
  }

  return (
    <div>
      <Head>
        <title>We Love Jokes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>
      <AppBar position="relative">
        <Toolbar>
          <Typography variant="h6" color="inherit" noWrap>
            We Love Jokes
          </Typography>
        </Toolbar>
      </AppBar>
      <main>
        <Container maxWidth="sm">
          <Box
            sx={{
              bgcolor: 'background.paper',
              pt: 8,
              pb: 6,
            }}
          >
            <Typography variant="h5" align="center" color="text.primary" paragraph>
              {joke.setup}
            </Typography>
            <Typography
              component="h1"
              variant="h4"
              align="center"
              color="text.secondary"
              gutterBottom
            >
              {joke.punchline}
            </Typography>
            <Box
             display="flex"
             justifyContent="center"

            >
              <Button
                variant="contained"
                onClick={getNewJoke}
              >
                Get New Joke
              </Button>
            </Box>
          </Box>
          {recentJokes.map((item, index) => 
            <Paper sx={{m:2, p:2}} key={index}>
              <Typography variant="h5" align="center" color="text.primary" paragraph>
                {item.setup}
              </Typography>
              <Typography
                component="h1"
                variant="h4"
                align="center"
                color="text.secondary"
                gutterBottom
              >
                {item.punchline}
              </Typography>
            </Paper>
          )}
        </Container>
      </main>
    </div>
  )
}
