import NavBar from "@/components/NavBar";
import UILibGroup from "@/components/UILibGroup";
import UILibList from "@/components/UILibList";
import Head from "next/head";
import { Button } from "react-bootstrap";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Button variant="primary">Primary</Button>
      <UILibList data={UI_LIBRARY_LIST}/>
      <UILibGroup>{UI_LIBRARY_LIST}</UILibGroup>
      <h1>Hi</h1>
      <PersonCard data={persons[0]}/>
    </>
  );
}

const persons = [
  {
    id: 1,
    fname: "Ali",
    lname: "Rezaei",
    email: "ali.rezaei@example.com",
    phone: "123-456-7890",
    pic: "https://randomuser.me/api/portraits/men/1.jpg",
    skills: ["JavaScript", "React", "Node.js"]
  },
  {
    id: 2,
    fname: "Sara",
    lname: "Moradi",
    email: "sara.moradi@example.com",
    phone: "234-567-8901",
    pic: "https://randomuser.me/api/portraits/women/2.jpg",
    skills: ["Python", "Django", "Machine Learning"]
  },
  {
    id: 3,
    fname: "Hassan",
    lname: "Karimi",
    email: "hassan.karimi@example.com",
    phone: "345-678-9012",
    pic: "https://randomuser.me/api/portraits/men/3.jpg",
    skills: ["Java", "Spring", "SQL"]
  }];

const UI_LIBRARY_LIST = [
	{
		name: "MUI",
		url: "https://mui.com/"
	},
	{
		name: "React Bootstrap (the one we're looking at)",
		url: "https://react-bootstrap.github.io/"
	},
	{
		name: "Ant Design",
		url: "https://ant.design/docs/react/introduce"
	},
	{
		name: "Semantic UI",
		url: "https://react.semantic-ui.com/"
	}
]
