import NavBar from "@/components/NavBar";
import UILibGroup from "@/components/UILibGroup";
import UILibList from "@/components/UILibList";
import Head from "next/head";
import { Button } from "react-bootstrap";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Button variant="primary">Primary</Button>
      <UILibList data={UI_LIBRARY_LIST}/>
      <UILibGroup>{UI_LIBRARY_LIST}</UILibGroup>
      <h1>Hi</h1>
    </>
  );
}

const UI_LIBRARY_LIST = [
	{
		name: "MUI",
		url: "https://mui.com/"
	},
	{
		name: "React Bootstrap (the one we're looking at)",
		url: "https://react-bootstrap.github.io/"
	},
	{
		name: "Ant Design",
		url: "https://ant.design/docs/react/introduce"
	},
	{
		name: "Semantic UI",
		url: "https://react.semantic-ui.com/"
	}
]